// Feature: after-party-lottery, Property 14: Letter-formation precondition gate
//
// @vitest-environment jsdom
//
// Validates: Requirements 6.2
//
// Property 14 asserts the load-time precondition gate of the lottery animation
// state machine in web/lottery/main.mjs (design §2.2 state diagram, task 10.2).
//
// Requirement 6.2: IF the /lottery/participants request fails OR returns fewer
// than 10 participants, THE Lottery_Page SHALL display an error message and SHALL
// NOT attempt the letter-formation sequence.
//
// Restated as a machine invariant: for ANY failure scenario, driving
// `createLotteryApp(...).run()` to completion must
//   (a) never visit LetterA / LetterW / LetterS / SphereForming / SphereIdle, and
//   (b) terminate in the Error state.
//
// We drive the real state machine in a jsdom environment with a MOCKED `fetch`
// and a stub scene. We deliberately do NOT inject `loadFont`,
// `createNicknameMesh`, or `createSphereFormation`: on the failure path none of
// those Three.js-dependent factories may be reached, so their absence (combined
// with the never-visit-formation-states assertion and a stub scene whose `add`
// is asserted to be never called) proves the sequence never started.
//
// Failure scenarios generated by fast-check:
//   (a) a 200/ok participants payload with count 0..9 (and a participants array
//       of matching length) → loadParticipants throws `too_few_participants`;
//   (b) the mocked fetch rejects (network error) → loadParticipants throws
//       `fetch_failed`;
//   (c) a non-ok / HTTP >= 500 response → loadParticipants throws `fetch_failed`.

import { describe, it, expect } from 'vitest';
import fc from 'fast-check';

import { createLotteryApp, State } from '../../main.mjs';

// ---------------------------------------------------------------------------
// Fixtures / helpers
// ---------------------------------------------------------------------------

/** The states that may only be reached once the >= 10 precondition is met. */
const FORBIDDEN_STATES = [
  State.LetterA,
  State.LetterW,
  State.LetterS,
  State.SphereForming,
  State.SphereIdle,
];

/**
 * A minimal stub scene satisfying the failure-path surface of `createLotteryApp`.
 * Records `add` calls so the test can assert no nickname mesh / sphere group was
 * ever added to the scene (which only happens on the success formation path).
 */
function makeStubScene() {
  return {
    onReveal: null,
    camera: null,
    addCalls: 0,
    add() {
      this.addCalls += 1;
    },
    remove() {},
    queueReveal(winner) {
      if (typeof this.onReveal === 'function') this.onReveal(winner);
    },
  };
}

/**
 * Build a Response-like mock fetch for a given failure scenario. The returned
 * function ignores its arguments (including the AbortController signal) and
 * resolves/rejects synchronously per the scenario.
 *
 * @param {object} scenario
 * @returns {(url: string, opts?: object) => Promise<object>}
 */
function makeFetch(scenario) {
  return async function mockFetch() {
    if (scenario.kind === 'network_error') {
      // (b) fetch itself rejects — a network / DNS / abort-style failure.
      throw new TypeError('Failed to fetch');
    }
    if (scenario.kind === 'http_error') {
      // (c) a reachable server returning a non-ok / >= 500 status.
      return {
        ok: scenario.status >= 200 && scenario.status < 300,
        status: scenario.status,
        json: async () => ({ count: 0, participants: [] }),
      };
    }
    // (a) a healthy 200 response, but with fewer than 10 participants.
    const participants = Array.from({ length: scenario.count }, (_, i) => ({
      nickname: `player-${i}`,
    }));
    return {
      ok: true,
      status: 200,
      json: async () => ({ count: scenario.count, participants }),
    };
  };
}

// Failure scenarios:
//   (a) too few participants — count is in [0, 9].
//   (b) network error — fetch rejects.
//   (c) HTTP error — a non-ok / >= 500 status (the client fails fast on both).
const arbScenario = fc.oneof(
  fc.integer({ min: 0, max: 9 }).map((count) => ({ kind: 'too_few', count })),
  fc.constant({ kind: 'network_error' }),
  fc
    .constantFrom(500, 502, 503, 504, 400, 404)
    .map((status) => ({ kind: 'http_error', status })),
);

// ---------------------------------------------------------------------------

describe('Property 14: Letter-formation precondition gate', () => {
  it('any fetch failure or count < 10 ⇒ never forms letters/sphere, ends in Error', async () => {
    await fc.assert(
      fc.asyncProperty(arbScenario, async (scenario) => {
        // Fresh DOM each run, including the error overlay the machine reveals.
        document.body.innerHTML = '<div id="error-overlay" hidden></div>';

        const scene = makeStubScene();
        const visited = [];

        const app = createLotteryApp({
          scene,
          document,
          fetch: makeFetch(scenario),
          now: () => Date.now(),
          apiBase: 'https://lottery.example.test',
          // Deliberately omit loadFont / createNicknameMesh / createSphereFormation:
          // none of them may be reached on the failure path (Requirement 6.2).
        });

        // Subscribe BEFORE run() so every visited state is recorded.
        app.subscribe((state) => visited.push(state));

        await app.run();

        // (a) The letter/sphere formation states are never visited.
        for (const forbidden of FORBIDDEN_STATES) {
          expect(visited).not.toContain(forbidden);
        }

        // (b) The machine terminates in the Error state.
        expect(app.state).toBe(State.Error);
        expect(visited).toContain(State.Error);

        // The formation path adds meshes / the sphere group to the scene; on the
        // failure path nothing is ever added.
        expect(scene.addCalls).toBe(0);

        // The error overlay is revealed (the displayed error message, Req 6.2).
        expect(document.getElementById('error-overlay').hidden).toBe(false);

        app.stop();
      }),
      { numRuns: 200 },
    );
  });
});
